"""Add categoryfield to Book model

Revision ID: 192ba8d64661
Revises: c58992262dc7
Create Date: 2025-03-12 14:01:16.712631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '192ba8d64661'
down_revision = 'c58992262dc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=225), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
